### ISSUE TITLE
move hero translations

### ISSUE THREAD

**Issue by gyst** [collective/plone.app.locales#102]
Following https://github.com/plone/Products.CMFPlone/pull/1374 two strings are moved from `hero.pt` into `plone-frontpage.pt`. This means that the `front-text` message id now needs to support also those moved strings.

The end result should be visually identical to before the change. It's a clean refactor, not a text change.

**Comment by jensens** [comment]
@gyst Is this one open by accident (so we can close it) or is something open? I just lost track here.

**Comment by jensens** [comment]
look like this one was solved already, please reopen if I’m wrong.
