### ISSUE TITLE
German: "Ort" is misleading for Path Criteria in Querystrings

### ISSUE THREAD

**Issue by jensens** [collective/plone.app.locales#117]
The German Word "Ort" used a a collection/ querystring criteria in is misleading for the actual meaning "Location in the Site" vs. the also existing "Location of an Event". 

A better word is probably "Pfad in der Seite" or just "Pfad". Another option is the word "Stelle".

Original in English its "Location" - I'am not sure if this is also misleading.

/cc @chrimba 

German speaking readers in here: Opinions?

**Comment by staeff** [comment]
@jensens "Ort" gives me the wrong impression as well. For me "Pfad" sounds best for this purpose.
