### ISSUE TITLE
Roles translations

### ISSUE THREAD

**Issue by gil-cano** [collective/plone.app.locales#118]
Creating a new spanish Plone site, I notice the following:
[Site Setting] (https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/interfaces/controlpanel.py#L1211) uses plone.app.vocabularies.Roles vocabulary which try to  [translate the roles names] (https://github.com/plone/plone.app.vocabularies/blob/master/plone/app/vocabularies/security.py#L66) but "Anonymous" and  "Authenticated" roles are not being translated. Should these be added to [plone-manual.pot?] (https://github.com/collective/plone.app.locales/blob/master/plone/app/locales/locales/plone-manual.pot)

**Comment by vincentfretin** [comment]
yes

**Comment by vincentfretin** [comment]
I'm taking care of it.

**Comment by vincentfretin** [comment]
@gil-cano
I resynced the translations, you can update your translation.

**Comment by gil-cano** [comment]
Thanks!
