### ISSUE TITLE
No/outdated docs on how to regenerate the pot/ sync the po files

### ISSUE THREAD

**Issue by jensens** [collective/plone.app.locales#121]
in docs folder there is nothing
then I found
https://github.com/collective/plone.app.locales/blob/master/utils/README.txt
which targets svn/Plone 4.0

Are I'am missing some docs? Google does not help much either, so http://docs.plone.org/develop/plone/i18n/contribute_to_translations.html does not help here as well.

**Comment by vincentfretin** [comment]
There is this issue too https://github.com/plone/documentation/issues/544
It's open in a tab in my browser for a while now.
The latest doc you can find is in this issue https://github.com/plone/Products.CMFPlone/issues/983
If someone want to contribute to update the documentation, please do. I'm doing less and less of Plone these days.

**Comment by vincentfretin** [comment]
I updated the contribute to i18n document https://github.com/plone/documentation/commit/672757452d6d9e183e5fb047399b4c963eb94a4c that has now a reference to plone.app.locales/utils/README.txt which has a reference to https://github.com/plone/Products.CMFPlone/issues/983
If you want to it better, please do.
