### ISSUE TITLE
Add documentation of Workflow between GitHub and Transifex

### ISSUE THREAD

**Issue by macagua** [collective/plone.app.locales#142]
Add documentation about the Workflow between GitHub and Transifex, for implements on plone.app.locales package

**Comment by macagua** [comment]
**Documentation in process** >> https://github.com/collective/plone.app.locales/wiki/Workflow-between-GitHub-and-Transifex

**Comment by tmassman** [comment]
@macagua, is transifex now save to use to update translations for Plone? Who is syncing the files between Plone and transifex?

**Comment by erral** [comment]
I am closing this as Transifex link is not anymore maintained.
