### ISSUE TITLE
Urgent: Broken Hebrew/RTL language sign-in pop-up window layout in Plone 5.0.7

### ISSUE THREAD

**Issue by MichaelPN** [collective/plone.app.locales#165]
The Issue arises after creating a new Plone site in RTL language/ or creating a site  translated by PAM in RTL language:

The Issue:   Log-in window runs to the right behind the visible area of the screen on normal/large screen/resolutions (it is PROBABLY  visible on mobile resolutions)

Steps to reproduce:

1.Create a new Plone site in Hebrew or Arabic (did not test on other RTL`s).
2. Sign Out.

3.Try to sign in: The Login window doesn`t seem to pop-up. Instead the whole page area is grayed out. The only resolution to someone who is informed about the problem is to resize the browser window to a  small/mobile size/resolution ,- then in the process of doing that he can see the log-in window comes back to the middle from behind the right border of the page.

Another way to reproduce this bug is to create a translation site with PAM from any language to RTL language, and then to repeat the steps described above.

Tested on two different monitors with same  result.
System is OpenSuse Leap 42.2(64-bit)
Tested on: 
Firefox for OpenSuse Leap  52.2.0 (64-bit)
Chrome 59.0.3071.115 (Official Build) (64-bit)

**Comment by vincentfretin** [comment]
This appears to be a ui issue, not a translation issue.
Can you please create a issue on https://github.com/plone/Products.CMFPlone/issues so it has more visibility and close this one? Thanks.

**Comment by MichaelPN** [comment]
Thank you very much for responding. Yes I will, of course. Should I include there the other bug related to cut-off descriptions in the tools menu as well? I filed two bugs in plone.app.locales.
Thanks in advance! 

    On Wednesday, September 6, 2017 3:09 PM, Vincent Fretin <notifications@github.com> wrote:
 

 This appears to be a ui issue, not a translation issue.
Can you please create a issue on https://github.com/plone/Products.CMFPlone/issues so it has more visibility and close this one? Thanks.—

**Comment by vincentfretin** [comment]
Yes please. And add a screenshot if you can.

**Comment by MichaelPN** [comment]
Hello again !   I posted the Bug for Plone 5 here https://github.com/plone/Products.CMFPlone/issues


I apologize for taking you time Sir , but would you please take a moment to look to see if we are talking about a BUGGY behavior or NOT in Plone 4.3.14 and Plone.App.Multilingual 2.0.3   ,since this  discussion seems to be going nowhere, while the multilingual support is very important to me if I want to use Plone. I have to wait until Plone 5 will be ready for good Hebrew support, and by then I decided to use Plone 4.3. The bugs(or not) described in the thread are really weird. The translation machinery behaves weird,-  wouldn't work neither with nor without Archetypes.Multilingual activated. There are at least two issues there seems to me. ONE with dexterity and ONE with Archetypes translations.   I tried to be very consistent when describing the issues, but the person that responded, seems to me, - didn't understand me correctly. May be you could clarify what is going on with translation machinery, please !Am I doing something wrong?
I first created issue on stackoverflow.com and then migrated it to Plone.community . If you follow my post carefully all the way to the end of the post ,- you will see that I am consistent. I am stuck without multilingual support and was very counting on it when started exploring Plone for that purpose.Hope you will have time to go over it, and sorry for that, but I appreciate very much if you try to help !!!
A possible bug in plone.app.multilingual /Please Help!

  
|  
|   |  
A possible bug in plone.app.multilingual /Please Help!
 Hello to everyone! Can anybody tell me please if I should file a bug for plone.app.multilingual ver.2.0.3 for Pl...  |  |

  |

 

Thank you indeed in advance,
Michael Papanyan
Netania, Israel  

    On Sunday, September 10, 2017 11:55 AM, Vincent Fretin <notifications@github.com> wrote:
 

 Yes please. And add a screenshot if you can.—

**Comment by vincentfretin** [comment]
Hi, sorry I have zero experience with plone.app.multilingual, I won't be of much help.
What thread are you referring about? Can you please add a link to it in https://github.com/plone/Products.CMFPlone/issues/2139 ? Please now continue the discussion there, thanks.

This issue was moved to https://github.com/plone/Products.CMFPlone/issues/2139

**Comment by MichaelPN** [comment]
on https://community.plone.org/t/a-possible-bug-in-plone-app-multilingual-please-help/4804/9
Sep '17
vincentfretin  wrote


On Plone 4.3, I think you need to install plone.app.contentypes profile to have a Dexterity Document content type. When you have the Document content types listed in Dexterity types, you will be able to enable the PAM behaviour I guess.


4 months later
MichaelPN
Jan 20

Hello, sorry it took me too long to respond to this. But yes that is true! I had to install plone.app.contentypes with buildout for this to work! So there is one problem here that I see.
The need to do the installation is not described anywhere in Plone documentation except the one and single place : the plone.app.contentypes manual pages. So for someone to use the content types he should be directed to that manual at least. But why would he look in there if he does not know he needs it ??!! So there is a need to inform users in more places, i think.
But meanwhile and despite it working well with dexterity (plone.app.contentypes),PAM for Plone 4.3 still behaves erroneously when used only with archetypes as described at the start of the thread.
