### ISSUE TITLE
Plone 5.0.7 user interface black toolbar in hebrew site has incomplete/cut descriptions

### ISSUE THREAD

**Issue by MichaelPN** [collective/plone.app.locales#166]
After creating a new site in Hebrew and loging-in,  the black toolbar on the left is BARELY USABLE if you don`t know the icon meanings, because the descriptions that are mixed in English and Hebrew
 **are cut off, so are incomplete**.

Additionally,
someone intuitively would probably expect that toolbar to be on the right side for RTL languages.
The same and even MUCH MORE IMPORTANT goes  for pages and objects that appear in the horizontal Navigation Menu of the site . 
Any page/object that you add to  the site menu,  **adds from left to right** on any theme installed. And the menu itself is on the left. It is counter-intuitive  for RTL designs  especially while all other objects and page descriptions are displayed right to left.
Here is the screenshot from demo.plone.de with all the problems visible :
https://www.dropbox.com/s/8gz3d12zu47ou5y/Screenshot_Plone_5.0.8_Hebrew.jpeg?dl=0

**Comment by vincentfretin** [comment]
This issue was moved to https://github.com/plone/Products.CMFPlone/issues/2140
