### ISSUE TITLE
Incorrect links and strings in ES plone.po

### ISSUE THREAD

**Issue by paskyorg** [collective/plone.app.locales#167]
In accessibility-info page, links to http://www.w3.org/TR/WCAG20/ and http://www.w3.org/TR/ATAG20/ are wrong.

These links are:

- http://mysite/"http://www.w3.org/TR/WCAG20//" instead http://www.w3.org/TR/WCAG20
- http://mysite/"http://www.w3.org/TR/ATAG20//" instead http://www.w3.org/TR/ATAG20/

**Comment by paskyorg** [comment]
# diff plone.po  plone-new.po
6909c6909
< msgstr "Este sitio utiliza el Sistema de Gestión de Contenidos de código abierto ${plone}. Cumple con las Pautas de Accesibilidad para el Contenido Web (<a href=\\\"http://www.w3.org/TR/WCAG20/\\\">${wcag} v2.0</a>}) nivel 'AA' para personas discapacitadas, incluyendo ceguera y visión reducida, sordera y pérdida auditiva, limitaciones cognitivas, movilidad reducida, trastornos del habla, fotosensibilidad, y combinaciones de éstas."
---
> msgstr "Este sitio utiliza el Sistema de Gestión de Contenidos de código abierto ${plone}. Cumple con las Pautas de Accesibilidad para el Contenido Web (<a href=\"http://www.w3.org/TR/WCAG20/\">${wcag} v2.0</a>}) nivel 'AA' para personas discapacitadas, incluyendo ceguera y visión reducida, sordera y pérdida auditiva, limitaciones cognitivas, movilidad reducida, trastornos del habla, fotosensibilidad, y combinaciones de éstas."
6914c6914
< msgstr "También es accesible a autores de contenido con discapacidad por el nivel 'AA' de las Pautas de Accesibilidad para Herramientas de Autor (<a href=\\\"http://www.w3.org/TR/ATAG20/\\\">${atag} 2.0</a>})."
---
> msgstr "También es accesible a autores de contenido con discapacidad por el nivel 'AA' de las Pautas de Accesibilidad para Herramientas de Autor (<a href=\"http://www.w3.org/TR/ATAG20/\">${atag} 2.0</a>})."
7153,7154c7153,7154
< "Este formulario le permite editar directamente la representación XML del listado de campos. Esto posibilita añadir anotaciones para grupos de cambios, validaciones y widgets. Ver la sección <a href=\\\"http://docs.plone.org/external/plone.app.dexterity/docs/reference/dexterity-xml.html\\\">Dexterity XML</a> del <a href=\\\"http://docs.plone.org/external/plone.app.dexterity/\n"
< "docs/index.html\\\">Manual de Desarrollador de Dexterity</a> para obtener más detalles."
---
> "Este formulario le permite editar directamente la representación XML del listado de campos. Esto posibilita añadir anotaciones para grupos de cambios, validaciones y widgets. Ver la sección <a href=\"http://docs.plone.org/external/plone.app.dexterity/docs/reference/dexterity-xml.html\">Dexterity XML</a> del <a href=\"http://docs.plone.org/external/plone.app.dexterity/\n"
> "docs/index.html\">Manual de Desarrollador de Dexterity</a> para obtener más detalles."
8250c8250
< msgstr "Si está seleccionado, permite eliminar los comentarios propios para los usuarios con el permiso \\\"Eliminar comentarios\\\""
---
> msgstr "Si está seleccionado, permite eliminar los comentarios propios para los usuarios con el permiso \"Eliminar comentarios\""
8279c8279
< msgstr "Si está seleccionado, permite modificar los comentarios a los usuarios con el permiso \\\"Modificar comentarios\\\""
---
> msgstr "Si está seleccionado, permite modificar los comentarios a los usuarios con el permiso \"Modificar comentarios\""

**Comment by paskyorg** [comment]
[plone.po.zip](https://github.com/collective/plone.app.locales/files/1155663/plone.po.zip)

**Comment by erral** [comment]
I'm sorry but I don't see the error in the po files.

In which version of Plone do you see the error?

**Comment by paskyorg** [comment]
My Plone version is 5.0.7, with plone.app.locales 5.0.13.

**Comment by erral** [comment]
I see some backslash-es scaping the URLs, maybe that's the problem:

```
@@ -6917,12 +6917,12 @@ msgstr "Parte del contenido en el asunto, código del correo, destinatario de co
 #. Default: "This site uses the open source Content Management System ${plone}. It meets the Web Content Accessibility Guidelines (<a href=\"http://www.w3.org/TR/WCAG20/\">${wcag} v2.0</a>) level 'AA' for people with disabilities, including blindness and low vision, deafness and hearing loss, learning disabilities, cognitive limitations, limited movement, speech disabilities, photosensitivity, and combinations of these."
 #: CMFPlone/browser/templates/accessibility-info.pt:21
 msgid "description_accessibility_info"
-msgstr "Este sitio utiliza el Sistema de Gestión de Contenidos de código abierto ${plone}. Cumple con las Pautas de Accesibilidad para el Contenido Web (<a href=\\\"http://www.w3.org/TR/WCAG20/\\\">${wcag} v2.0</a>) nivel 'AA' para personas discapacitadas, incluyendo ceguera y visión reducida, sordera y pérdida auditiva, limitaciones cognitivas, movilidad reducida, trastornos del habla, fotosensibilidad, y combinaciones de éstas."
+msgstr "Este sitio utiliza el Sistema de Gestión de Contenidos de código abierto ${plone}. Cumple con las Pautas de Accesibilidad para el Contenido Web (<a href=\"http://www.w3.org/TR/WCAG20/\">${wcag} v2.0</a>) nivel 'AA' para personas discapacitadas, incluyendo ceguera y visión reducida, sordera y pérdida auditiva, limitaciones cognitivas, movilidad reducida, trastornos del habla, fotosensibilidad, y combinaciones de éstas."
 
 #. Default: "It is also accessible to content authors with disabilities per the level 'AA' Authoring Tool Accessibility Guidelines (<a href=\"http://www.w3.org/TR/ATAG20/\">${atag} 2.0</a>)."
 #: CMFPlone/browser/templates/accessibility-info.pt:29
 msgid "description_accessibility_info2"
-msgstr "También es accesible a autores de contenido con discapacidad por el nivel 'AA' de las Pautas de Accesibilidad para Herramientas de Autor (<a href=\\\"http://www.w3.org/TR/ATAG20/\\\">${atag} 2.0</a>)."
+msgstr "También es accesible a autores de contenido con discapacidad por el nivel 'AA' de las Pautas de Accesibilidad para Herramientas de Autor (<a href=\"http://www.w3.org/TR/ATAG20/\">${atag} 2.0</a>)."

```

@macagua how should we handle the spanish translation, are you using transifex or should we commit directly here?

**Comment by erral** [comment]
@macagua ping

**Comment by erral** [comment]
@macagua ping :)

**Comment by erral** [comment]
No response from @macagua, so I am going to commit the changes directly here.

**Comment by gforcada** [comment]
@erral should this be kept open?

**Comment by erral** [comment]
No, just close and go :)
