### ISSUE TITLE
Translation for plone.app.content

### ISSUE THREAD

**Issue by l34marr** [collective/plone.app.locales#185]
I guess the translation for plone.app.content is moved to plone.app.locales, or somewhere else? How can I update the plone.app.content translation for Plone 5.x in this case? For example https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/constraintypes.py#L136

**Comment by vincentfretin** [comment]
This code needs to be modified to use simply `_` and not `PC_`. Can you create a PR for plone.app.content? This is why the messages are not extracted. They should ends up in plone.po after this change.

**Comment by malikrohit16** [comment]
So this means just changing PC_ to _ in https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/constraintypes.py#L136 will solve the problem?
If so I am willing to create the PR

**Comment by vincentfretin** [comment]
That's right. I will resync the po files once your PR is merged. Thanks in advance @malikrohit16

**Comment by malikrohit16** [comment]
I tried but I think it won't be merged until my contributor agreement is approved.

**Comment by vincentfretin** [comment]
If you signed it and sent it, it's ok. I merged it (https://github.com/plone/plone.app.content/pull/153) and added a changelog entry in plone.app.content.
I resynced the po files, 8 messages were added.

**Comment by vincentfretin** [comment]
And I got back the translations for those 8 messages from the 4.3.x branch and released a new plone.app.locales version 5.1.7.
