### ISSUE TITLE
Poedit rewrites comments to be multiline

### ISSUE THREAD

**Issue by erral** [collective/plone.app.locales#187]
I have seen [this commit](https://github.com/collective/plone.app.locales/commit/3cd391227c79cf05000c1e5656e0ab23dbb2a417) by @mauritsvanrees fixing spanish po files. 

I have realised that it's my poedit's fault, so this may have happened also with basque po files. I have reset my poedit settings and it keeps rewriting the comments to be onliner, but also removes texts from those comments...

See a diff of po file after opening the file with poedit, saving it (without changes) and closing poedit:

```
@@ -915,7 +915,7 @@ msgid "Block styles"
 msgstr "Bloke-erako estiloak"
 
 #. Default: "Boolean (True/False)"
-#: criterion description of criterion ATBooleanCriterion
+#: criterion description of ATBooleanCriterion
 msgid "Boolean (True/False)"
 msgstr "Boolearra (egiazkoa/faltsua)"
 
@@ -1290,8 +1290,7 @@ msgstr "Dauka"
 msgid "Contains objects"
 msgstr "Elementuak ditu barnean"
 
-#: CMFPlone/PloneControlPanel.py:69
-#: CMFPlone/browser/templates/author.pt:201
+#: CMFPlone/PloneControlPanel.py:69 CMFPlone/browser/templates/author.pt:201
 msgid "Content"
 msgstr "Edukia"
 
@@ -1763,12 +1762,14 @@ msgid "Discussion"
 msgstr "Eztabaida"
 
 #. Default: "Discussion Item"
-#: portal type title of type with description Discussion Items are documents which reply to other content.They should *not* be addable through the standard 'folder_factories' interface.
+#: portal type title of with description Discussion Items are documents which
+#: reply to other content.They should *not* be addable through the standard
+#: 'folder_factories' interface.
 msgid "Discussion Item"
 msgstr "Eztabaida elementua"

```

Has anyone seen anything similar?

**Comment by erral** [comment]
I have tested with different versions of poedit (1.8.x and 2.0.x) and both versions do the same.

**Comment by mauritsvanrees** [comment]
I don't know. I am not using `poedit`.
You could fix things after you are done by doing `i18ndude sync plone.pot es/LC_MESSAGES/plone.po`.

I can imagine that `poedit` wraps lines differently. `i18ndude` has settings for that.

But this change amazes me:

```
-#: criterion description of criterion ATBooleanCriterion
+#: criterion description of ATBooleanCriterion
```

I can't imagine why `poedit` would think that the string `criterion` would need to be removed.

Note: as far as I see, nothing gets broken by `poedit`. These are just comments that will have no influence on the Plone UI.

**Comment by erral** [comment]
Thanks for the pointer, that's what I will do.
