### ISSUE TITLE
Make the i18ndude matrix available to everyone

### ISSUE THREAD

**Issue by hvelarde** [collective/plone.app.locales#189]
Can we run `i18ndude list -p plone` on every build and save the result somewhere to make it easier to know the status of translations?

for more context see: https://community.plone.org/t/plone-5-1-translations/6006/11?u=hvelarde

**Comment by gforcada** [comment]
Yes, that's been on my TODO list for quite a while, but that would be just part of the puzzle, the other half, checking if there are new translation strings needs to go together. It would be quite disappointing to update a translation just to see that overnight 50 new strings are also missing...

**Comment by hvelarde** [comment]
I agree, but let's fix one problem at a time ;)

**Comment by gforcada** [comment]
See https://jenkins.plone.org/view/Translations the jobs that are currently failing have already tickets to where the fix should go.
