### ISSUE TITLE
Remove references to plone.app.collection

### ISSUE THREAD

**Issue by hvelarde** [collective/plone.app.locales#218]
Seems to me this package is no longer used in Plone 5; I don't know why is being referenced in plone.app.locales.

**Comment by vincentfretin** [comment]
`plone.app.collection` is still referenced in 
https://github.com/plone/buildout.coredev/blob/9b6ebc1318a0fa1deadea8c4b503e604eed591de/experimental/i18n.cfg#L82
for messages extraction, and I think you can still have Plone 5.2.x with Archetypes collections with plone.app.collection on Python 2.7, but we can probably remove it for Plone 6 (#315).
https://github.com/plone/buildout.coredev/blob/9b6ebc1318a0fa1deadea8c4b503e604eed591de/versions.cfg#L311

**Comment by erral** [comment]
This was removed for Plone 6 by https://github.com/plone/buildout.coredev/commit/3130640e984d345534cec99b9b9b823e9a8ce5e5
