### ISSUE TITLE
Encoding of .po files other than in UTF-8 ?

### ISSUE THREAD

**Issue by pysailor** [collective/plone.app.locales#234]
Hi,
I have a plone5 app that uses a calendar widget. In Lithuanian (LT), some month names look broken:

<img width="362" alt="screen shot 2018-08-08 at 17 14 12" src="https://user-images.githubusercontent.com/642660/43846678-319610a0-9b2f-11e8-99e0-7a357668e8d6.png">

The reason seems to be that the plonelocales.po is encoded using iso-8859-13. If I switch that to utf-8, like I did in this branch:
https://github.com/collective/plone.app.locales/compare/pysailor-utf8-encoding-lt
then all looks fine:

<img width="362" alt="screen shot 2018-08-08 at 17 15 21" src="https://user-images.githubusercontent.com/642660/43846761-67e86504-9b2f-11e8-9bc7-5f66a57b2803.png">

My problem might be quite specific, since my calendar widget (pat-date-picker from https://github.com/Patternslib/Patterns) expects all text elements as utf-8 encoded strings. But when I create those strings, I just use `zope.i18n.translate()` for all the month names using `MessageFactory('plonelocales')`, and I don't see how to make that aware of a different encoding of the .po file.

Is there any good reason not to use utf-8 for all .po files? Would my branch be a legitimate PR? Should I ask the "Last Translator" about this?

Thanks,
Wolfgang

**Comment by vincentfretin** [comment]
Hi, please do a PR to reencode it in utf-8, that's fine by me.
