### ISSUE TITLE
Resync of plone.app.locales

### ISSUE THREAD

**Issue by erral** [collective/plone.app.locales#250]
@vincentfretin can we have a resync of plone.app.locales with the current coredev to prepare the translations for the 5.2 release?

**Comment by vincentfretin** [comment]
I resynced with those two changes
https://github.com/plone/Products.CMFPlone/pull/2821
https://github.com/plone/plone.app.caching/pull/47

https://github.com/collective/plone.app.locales/commit/742eea7630d6efeeaa8d3a9b37a2920269ddbf97
https://github.com/collective/plone.app.locales/commit/dc5f3f40cf16f7cc2fd73e81170ab8b19f4e043d
