### ISSUE TITLE
French: Typo "Content-Type"

### ISSUE THREAD

**Issue by ksuess** [collective/plone.app.locales#311]
hi @vincentfretin 
probably Content-Type not Contenu-Type: 
https://github.com/collective/plone.app.locales/blob/ba857dc47dfa6343444bdc89de433129bec6cb86/plone/app/locales/locales/fr/LC_MESSAGES/plone.po#L13878

**Comment by ksuess** [comment]
Here are a few to many $$      
;-)

#. Default: "From: {encoded_mail_sender}\nTo: {email}\nSubject: Your username for {portal_url}\nContent-Type: text/plain\nPrecedence: bulk\n\nDear {fullname},\n\nYou requested to be reminded of your username for {portal_url}.\nYour username is: {login}\n\n\nWith kind regards,\n\n--\n\n{email_from_name}"
#: CMFPlone/browser/login/login_help.py:28
msgid "mailtemplate_username_info"
msgstr ""
"From: ${encoded_mail_sender}\n"
"To: ${email}\n"
"Subject: Votre nom d'utilisateur pour ${portal_url}\n"
"Contenu-Type: text/plain\n"
"Precedence: bulk\n"
"\n"
"Cher ${fullname},\n"
"\n"
"Vous avez demandé de vous rappeler votre nom d'utilisateur pour ${portal_url}.\n"
"Votre nom d'utilisateur est : ${login}\n"
"\n"
"Avec nos meilleures salutations,\n"
"\n"
"-- \n"
"\n"
"${email_from_name}"

**Comment by vincentfretin** [comment]
Oh my! Thank you. I'll fix it.

**Comment by vincentfretin** [comment]
Some days ago I tested this feature and got "SMTPRecipientsRefused: Recipient address rejected by server." error but I didn't dig further, this was this!

**Comment by vincentfretin** [comment]
I fixed it in French. I fixed Catalan that was having the same issue.
