### ISSUE TITLE
New 4.3 release?

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/plone.app.locales#312]
Last release was over two years ago. The only commits since then were packaging related changes by me:
https://github.com/collective/plone.app.locales/commits/4.3.x
So not really interesting, except that one of the changes fixes the ReStructuredText for PyPI, which is broken for this release:
https://pypi.org/project/plone.app.locales/4.3.16/

Are any real changes needed?
Does anyone wish to add a few more translations?

(Plone 5.2.2 should finally *really* be almost final now, so I am getting a few things moving for 4.3 and 5.1.)

**Comment by vincentfretin** [comment]
I can do a new release just for ReStructuredText fix. :)

**Comment by vincentfretin** [comment]
I backported some new translations from Plone 5.2
https://github.com/collective/plone.app.locales/commit/05cd08c28fd881b5b32adf9b60a7807ce27c9584
For reference, I did it like this:
```
buildout.coredev-4.3/src/plone.app.locales (4.3.x) $ for lg in af ar bg bn ca cs cy da de el en en_AU en_GB eo es et eu fa fi fr fu gl he hi hr hu hy id it ja ka kn ko lt lv mi mk_MK my nl nn no pl pt pt_BR rm ro ru sk sl sm sq sr sr_Latn sv ta te th to tr uk vi zh_CN zh_HK zh_TW; do i18ndude admix plone/app/locales/locales/$lg/LC_MESSAGES/plone.po ../../../buildout.coredev-5.2/src/plone.app.locales/plone/app/locales/locales/$lg/LC_MESSAGES/plone.po >/tmp/plone.po && mv /tmp/plone.po plone/app/locales/locales/$lg/LC_MESSAGES/plone.po; done
```

**Comment by vincentfretin** [comment]
https://pypi.org/project/plone.app.locales/4.3.17/ released

**Comment by mauritsvanrees** [comment]
Thanks a lot!
