### ISSUE TITLE
Release for 5.1.7

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/plone.app.locales#313]
I am making a [Plone 5.1.7rc1](https://github.com/plone/Products.CMFPlone/issues/3182) as we speak.
Could we have a new plone.app.locales release?
The only changes since the last release of 14 July  are two updated German translations, so there is not much need. But I am happy include to a new release if there is one.

**Comment by vincentfretin** [comment]
plone.app.locales 5.1.25 released

**Comment by mauritsvanrees** [comment]
Thanks!
