### ISSUE TITLE
Update of the i18n team page

### ISSUE THREAD

**Issue by vincentfretin** [collective/plone.app.locales#314]
Hi everyone,

We need to update the [i18n team on plone.org](https://plone.org/community/internationalization)
@cdw9  just gave me the permission to modify this page.

Does anyone still use IRC? Does the channel plone.org still exist?
I think we can remove reference to IRC there.

For the list of members, I think this list is quite old, lots of inactive members.
Same for https://github.com/collective/plone.app.locales/blob/master/docs/TRANSLATORS.html I think it's very old info, and there is no rendering of this page!
I propose to remove TRANSLATORS.html from the repo, remove the old list of members on the i18n page, and create a new one based on latest active contributors like I did in https://github.com/collective/plone.app.locales/issues/294#issuecomment-646071169 and really add github handles instead of irc nickname. And maybe add which language has not current maintainer?
What do you think? If you don't want to be listed there, please tell me. If you want to be listed, please also tell me. :-)

There is still mention of the plone-i18n mailing-list that has long been inactive (maybe it already has been archived or removed, I'm not sure). Instead we need to add a reference to the i18n category of the forum https://community.plone.org/c/development/i18nl10n/42
Do you want your local community to be listed there too? If yes, give me the link and eventually a small paragraph to add on the page.

If there is other changes you want to make to this page, please add a comment.

**Comment by erral** [comment]
Updated.
