### ISSUE TITLE
how can I help with translation - found wrong german word in locales

### ISSUE THREAD

**Issue by adnus** [collective/plone.app.locales#321]
Hi guys,

I'm not an expert programmer. But I managed it to create a new Theme for Plone.

While testing, I found this bad translation in plone.app.locales:

#. Default: "${date} from ${starttime}"
#: plone.app.event/plone/app/event/browser/formatted_date.pt:52
msgid "event_when_sameday_openend"
msgstr "${date} von ${starttime}"

should be

msgstr "${date} ab ${starttime}"

How can I help with translation OR how can I compile a new pod file for german?

Thanks and greetings
Jens

**Comment by ale-rt** [comment]
Hi and thanks for your interest in Plone.

Can you try to:
- browse to https://github.com/collective/plone.app.locales/blob/master/plone/app/locales/locales/de/LC_MESSAGES/plone.po
- click the edit icon 
- change the translation
- scroll to the bottom and propose the change (be sure to create a new branch, see screenshot attached)

![image](https://user-images.githubusercontent.com/1300763/108197519-cac61680-711a-11eb-9c5c-4f23922453d0.png)
![image](https://user-images.githubusercontent.com/1300763/108197693-03fe8680-711b-11eb-8a8a-291c875fbc06.png)

**Comment by adnus** [comment]
ok, did it. A new fork was created automaticly for me. Hope that's ok so far.
