### ISSUE TITLE
Release for 5.2.4

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/plone.app.locales#323]
Can we have a new plone.app.locales release for [Plone 5.2.4](https://github.com/plone/Products.CMFPlone/issues/3250) please? There have not been many changes, but would still be good.

@vincentfretin Are you still willing to do this?

Is there documentation on how to do this? I guess releasing is simply running `fullrelease`, I can handle that.

But actually taking care of the package, updating `pot` and `po` files, will be trickier.
Is https://github.com/plone/buildout.coredev/blob/5.2/experimental/i18n.cfg working and up to date?

**Comment by vincentfretin** [comment]
It's almost just `fullrelease` yes, but I also verify all the commits that was done as well. Here is what I do https://github.com/collective/plone.app.locales/blob/a4462e8564310a930f0917a29e6852aa96ff0e12/utils/RELEASING.rst nothing fancy. Yes https://github.com/plone/buildout.coredev/blob/5.2/experimental/i18n.cfg is up to date and https://docs.plone.org/develop/plone/i18n/contribute_to_translations.html is also up to date.

I'm willing to continue the releases for 5.2.x, it's just maintenance at this point.
I'm probably not going to spend time to sync translations for Plone 6 and fix all i18n issues if any with all the templates changes, like I used to though. So I'll probably ask for help here and wait for someone else to fix any i18n issues in the templates.

I released plone.app.locales 5.1.28.

**Comment by jensens** [comment]
If i18n.cfg is no longer experimental, why not move it to too level?

**Comment by jensens** [comment]
Ad Plone 6, we keep this in mind. I think we need a new major release dropping all the Archetypes specific translations anyway.

**Comment by vincentfretin** [comment]
LOL this is indeed not experimental at all. The `i18n.cfg` file was initially at the root when I created it in 2009-06-07 
It's Limi that moved it in `experimental/` in 2009-11-15 when moving other stuff. I didn't argue about it at this time.
OMG more than 11 years ago.
