### ISSUE TITLE
Some english translations lost

### ISSUE THREAD

**Issue by frapell** [collective/plone.app.locales#341]
Looking at this [commit](https://github.com/collective/plone.app.locales/blob/2c68ae375dc13c19b658a7d06ee2fc7bada12744/plone/app/locales/locales/en/LC_MESSAGES/plone.po) from @vincentfretin from Jul 1, 2020, and searching for `plone.formwidget.recurrence/plone/formwidget/recurrence/browser/i18n.py` there are several strings with the text in english.

The next [commit](https://github.com/collective/plone.app.locales/blob/7906b95c6fef0ee2d305719a9779b7365dfb63b1/plone/app/locales/locales/en/LC_MESSAGES/plone.po) on this file is from @erral on Sep 25, 2021 which deleted the file. It was restored it in the [next one](https://github.com/collective/plone.app.locales/blob/8b2090d9bbbc7a6a733117061403e9ed42e95def/plone/app/locales/locales/en/LC_MESSAGES/plone.po), however without the translated strings from `plone.formwidget.recurrence`.

This causes the recurrence widget in events to break

![image](https://user-images.githubusercontent.com/851006/153329738-c290f326-7321-45d4-8af2-ef99d12a96ab.png)

Using commit `852218838961a2a6c9a0764dd0074c6babf6f2a6` for plone.app.locales fixes the issue:

![image](https://user-images.githubusercontent.com/851006/153330705-25763b66-36bc-45db-b7c5-0ab422e823ee.png)

**Comment by erral** [comment]
This must be somehow related to when I merged some packages' translations into `plone` domain.

I will look at it and try to restore the previous translations.

**Comment by erral** [comment]
I recovered the translations, merged them into plone.po and resync the translation files to have everything synced.

See: https://github.com/collective/plone.app.locales/commit/4999e46f13c4f4b2305e9071040c87b787a55ac1#diff-c93c02947da8370b0a5ef3196d43cddfa9155862d18901c835ee1c5d092781feL10593
