### ISSUE TITLE
Release for Plone 6.0.0a4

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/plone.app.locales#343]
Could we have a new release please? I want to do an alpha 4 this week. See my checklist at https://github.com/plone/Products.CMFPlone/issues/3483

Also, I want to do a Plone 5.2 release this month, so a new release is welcome there as well, if needed.

**Comment by erral** [comment]
Released both packages:
- plone.app.locales 6.0.2
- plone.app.locales 5.1.31
