### ISSUE TITLE
widgets.pot is outdated

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/plone.app.locales#358]
Looks like `widgets.pot` is manually curated. The last bigger update was almost exactly two years ago, see the [history](https://github.com/collective/plone.app.locales/commits/master/plone/app/locales/locales/widgets.pot). This means the `widgets.pot` contains messages for patterns that are not used anymore, for example `thememapper` and `resourceregistry`.

Can we update this please?
Maybe there is documentation on how to do this, but I did not look.

**Comment by erral** [comment]
The last time I tried to do this I failed misserably but @petschki managed to update the file some weeks ago. Can you help us?

**Comment by petschki** [comment]
uh ... honestly since it was only one new `msgid` I added it manually in the .pot file and synced the .po files with i18ndude ...

**Comment by erral** [comment]
there us to be a `make i18n-dump` command in previous versions of mockup: https://github.com/plone/mockup/blob/4.x/Makefile#L106-L107

There used to be a i18n message extracting script in the Gruntfile, but there is no Gruntfile now:

https://github.com/plone/mockup/blob/4.x/mockup/Gruntfile.js#L117

So I guess we should write a script to do that and register it in the root package.json.

I will open an issue in the mockup repo.

**Comment by erral** [comment]
Fixed by https://github.com/collective/plone.app.locales/commit/564e2e601cd226e842b99a39a46cac9e966d2584
