### ISSUE TITLE
'msgid' and 'msgstr' entries do not both end with '\n'

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/plone.app.locales#365]
When in the `locales` directory, I check all po files with `msgfmt`, redirecting stderr/stdout to a file so I can properly grep for a fatal error:

```
$ for i in */*/*.po; do msgfmt -c $i; done &> x
$ grep -B1 fatal x
ca/LC_MESSAGES/plone.po:10856: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 1 fatal error
--
de/LC_MESSAGES/plone.po:14240: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 3 fatal errors
--
it/LC_MESSAGES/plone.po:13549: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 3 fatal errors
--
ru/LC_MESSAGES/plone.po:13549: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 1 fatal error
--
sl/LC_MESSAGES/plone.po:13513: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 1 fatal error
--
zh_TW/LC_MESSAGES/plone.po:13512: 'msgid' and 'msgstr' entries do not both end with '\n'
msgfmt: found 2 fatal errors
```

There are various warnings as well. But the fatal errors could mean that Plone fails to parse some po files at startup, causing missing translations.

This reminds me, it might be nice to have a few checks using GitHub actions.

**Comment by erral** [comment]
I fixed these errors in https://github.com/collective/plone.app.locales/commit/db1c7a93764a623bb2bf2e13fee8706271d40d64

And I added a GitHub Action that runs the gettext command to compile po files into mo in a PR (https://github.com/collective/plone.app.locales/pull/411)

So I think that we can close this.
