### ISSUE TITLE
Fuzzy translations are not used

### ISSUE THREAD

**Issue by davisagli** [collective/plone.app.locales#366]
Some messages are marked as "[fuzzy](https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html)" with this line:
```
#, fuzzy
```

~~These translations are skipped when python-gettext compiles the .po file into a .mo file: https://github.com/hannosch/python-gettext/blob/master/pythongettext/msgfmt.py#L104~~ I'm not completely sure where it's happening, but this seems to prevent the message from getting loaded.

This is why the "Summary" (description) field is untranslated in some languages, for example.

We can simply remove this line, but then maybe some translation tool will add it again. Maybe python-gettext needs an option for whether to include these or not.

**Comment by davisagli** [comment]
https://github.com/collective/plone.app.locales/blob/master/utils/RELEASING.rst mentions using `msgfmt` (part of gettext) to compile the .po files. I think we can add the `-f` flag to make msgfmt include the messages that are marked as fuzzy.

**Comment by davisagli** [comment]
But, since the fuzzy marker is intended to mark translations that may need further review, I think it's probably best if we do not include them, but ask translators to be sure to review and remove them.

**Comment by tisto** [comment]
@mauritsvanrees @erral I'd like to have a plone.app.locales release with our translation fixes. I am not sure if I can just make a release or if there is a specific process for plone.app.locales? Can you enlighten me or just make a release? :)

**Comment by erral** [comment]
I can't make a release until Sunday. The release process is simple, is documented here https://github.com/collective/plone.app.locales/blob/master/utils/RELEASING.rst

**Comment by erral** [comment]
@tisto I have just released plone.app.locales == 6.0.5 with the latest changes
