### ISSUE TITLE
Switched symbols in sharing tab description text

### ISSUE THREAD

**Issue by petschki** [collective/plone.app.locales#381]
In msgid `help_inherit_local_roles` the icons are wrongly switched ... the `image_link_icon` is for "global" and `image_link_icon` is for "inherited" permissions.

<img width="1015" alt="Bildschirm­foto 2022-11-24 um 09 07 08" src="https://user-images.githubusercontent.com/511761/203729385-334e0ad5-a29f-4793-ab97-33490c7e79fd.png">

*Note:* I saw on [6-classic](https://6-classic.demo.plone.org) that this is valid for german and spanish. English and Basque is correct

**Comment by erral** [comment]
I fixed this issue for `de` and `es` in https://github.com/collective/plone.app.locales/commit/cc73e2105250a5b84138dea17a49e7382d16483b and https://github.com/collective/plone.app.locales/commit/c1f945f18dbcd5e67d8511c9d49e95fc1b97c936
