### ISSUE TITLE
Updated Turkish translation

### ISSUE THREAD

**Issue by uyar** [collective/plone.app.locales#388]
I have created a repo for updating the Turkish translation (I'm also the original translator):

https://github.com/uyar/plone.app.locales.tr

I'm using this with a Plone 5.2.10 installation.

**Comment by erral** [comment]
Contribute those translations to the canonical translations packages, please. Here you have the documentations to do that:
https://6.docs.plone.org/i18n-l10n/contributing-translations.html#translate-plone-classic-ui

**Comment by uyar** [comment]
That repository is for Plone 6, I'm on Plone 5.2. There are removed messages from Plone 5.2 to Plone 6 which I need. I couldn't see how I can update the translations for Plone 5.2 and maybe later continue to Plone 6.

**Comment by erral** [comment]
There is a 5.1.x branch in that repo which contain the translations for 5.2.

Please open a PR for that and I will release a new version for Plone 5.2.

Then I can help you reusing those translations for 6.

**Comment by erral** [comment]
@uyar I have integrated your po files in plone.app.locales branch 5.1.x and released a new version with them

plone.app.locales = 5.1.32

https://pypi.org/project/plone.app.locales/5.1.32/

I will reuse those translations also for 6.x

**Comment by erral** [comment]
@uyar here is the update for Plone 6.0
https://github.com/collective/plone.app.locales/pull/395
