### ISSUE TITLE
msgid label_related_items is not in plone.app.locales

### ISSUE THREAD

**Issue by wesleybl** [collective/plone.app.locales#394]
`plone.app.relationfield` has the msgid [label_related_items](https://github.com/plone/plone.app.relationfield/blob/6e3d1b6827c14cc0a8d0e992ac3e553a85f46844/plone/app/relationfield/behavior.py#L19). But it is not listed in `plone.app.locales` po files.

**Comment by erral** [comment]
Fixed by https://github.com/plone/buildout.coredev/commit/04e78f73293c157674ab087027fed545449c6562
