### ISSUE TITLE
Plone 5.2 portuguese

### ISSUE THREAD

**Issue by ksuess** [collective/plone.app.locales#414]
**Describe the bug**
Plone 5.2 is not translated to portuguese if the site language is portuguese.

**To Reproduce**

- Create a Plone 5.2 vanilla site with site language portuguese.

**Expected behavior**
UI is translated.

**Screenshots**

**Software (please complete the following information):**

- Plone Version 5.2.13
- plone.app.locales branch 5.1.x (Plone 5.2 comes with plone.app.locales 5.1.33)

**Additional context**
Other site languages like italiano and german do translate the UI. 
Other languages like norsk do NOT translate the language.

**Comment by ksuess** [comment]
What I tried so far: 
https://github.com/collective/plone.app.locales/pull/413

**Comment by ksuess** [comment]
Hi, @erral, can you have a look? Any hint is welcome.

**Comment by erral** [comment]
@ksuess I have just created a vanilla Plone 5.2.13 and configured with Portuguese as language, and I see the interfaces correctly translated. See the screenshots:

![Pantaila-argazkia 2023-12-22 09-52-52](https://github.com/collective/plone.app.locales/assets/817365/15af40ae-3dcc-44d3-a242-f16325d0bc92)
![Pantaila-argazkia 2023-12-22 09-52-40](https://github.com/collective/plone.app.locales/assets/817365/151fe549-593d-4c0f-8e21-a7bc7272b723)
![Pantaila-argazkia 2023-12-22 09-52-25](https://github.com/collective/plone.app.locales/assets/817365/a7d3d662-6991-40cf-909a-3c270097dd8a)

To try to track this down, does you Zope instance compile the PO files to MO files?

You can force this to happen adding the following environment var in the Zope instance configuration:

```ini
[instance]
...
environment-vars = 
    zope_i18n_compile_mo_files true
    ...

```

**Comment by ksuess** [comment]
Oops, found this:

```
environment-vars =
    PTS_LANGUAGES de en fr it es
    zope_i18n_allowed_languages de en fr it es
```

Which obviously lacks of 'pt'.
