### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by gforcada** [collective/plone.app.locales#46]
Nearly all OSS projects have their specific website where translators can work on translations, see what's missing, etc.

What's the status/needs for Plone translators?

Is this up to date: https://www.transifex.com/projects/p/plone/ ?

For example:
https://l10n.gnome.org/languages/fr/gnome-3-16/ui/
http://l10n.kde.org/stats/gui/trunk-kde4/team/fr/
https://translations.launchpad.net/ubuntu/+translations
https://translations.documentfoundation.org/fr/

**Comment by vincentfretin** [comment]
I don't maintain the translations on transifex. We did an experiment some years ago but found some issues with the way the po files are synchronized. I can't remember exactly what the issues were.
Maybe the issues was resolved, I don't know. 
I see macagua recreated the plone project on transifex, you should ask him how he uses it and if he has any problem with it.

**Comment by datakurre** [comment]
@macagua What was your experience on transifex?

We'd like to use Transifex to get more people (also with less developer background) to participate in Finnish localization of plone to make it better quality. @macagua, how could I get update pot-files from plone.app.locales into Transifex?

I'd expect that i18ndude could be used to merge transifex po file updates into upstream po files.

**Comment by macagua** [comment]
@gforcada @datakurre Really I am sorry for the response your question, I had not seen this notification, @vincentfretin was referenced me about this! 

Then I working a proposal about the Workflow between GitHub and Transifex, here the following issues that I am working:

- https://github.com/collective/plone.app.locales/issues/140
- https://github.com/collective/plone.app.locales/issues/141
- https://github.com/collective/plone.app.locales/issues/142

**Comment by jensens** [comment]
I am a big fan of Zanata http://zanata.org/ which is FOSS and really integrates with Python well. A large customer of mine uses it and in future, we plan a tighter integration with Plone.

**Comment by erral** [comment]
Transifex is not maintained and community did not reach any consensus using a web based platform. We have translation stats available via Jenkins here: https://jenkins.plone.org/view/Translations/
