### ISSUE TITLE
Contributor agreement?

### ISSUE THREAD

**Issue by idgserpro** [collective/plone.app.locales#82]
Is required contributor agreement to contribute to this repository?

**Comment by idgserpro** [comment]
@polyester ?

**Comment by polyester** [comment]
no, it's in the Collective, so not needed

**Comment by gforcada** [comment]
Maybe a small paragraph on the README will help remind everyone about it :)

**Comment by gforcada** [comment]
What about this: https://github.com/collective/plone.app.locales/commit/f6b0593160db8f59c874313e819a05f5b320de4e
