### ISSUE TITLE
Add translation to plone.protect in Plone 4.3

### ISSUE THREAD

**Issue by idgserpro** [collective/plone.app.locales#86]
The commit https://github.com/collective/plone.app.locales/commit/1b5674ce51ba2ec35adc4cbb4558eaea76fba7cd of @vincentfretin doesn't add translations for [plone.protect](https://github.com/plone/plone.protect/blob/dc58d3beabf17df6ec480779abf30522ccb1b926/plone/protect/confirm.pt) in Plone 4.3.

**Comment by vincentfretin** [comment]
Thanks @idgserpro I didn't pay attention. This is fixed.
